/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IScatterToken__factory } from "./IScatterToken__factory";
export { ScatterStaking__factory } from "./ScatterStaking__factory";
