/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IScatterToken } from "./IScatterToken";
export type { ScatterStaking } from "./ScatterStaking";
