/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ScatterStakingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateFarmingReward"
      | "farmingBalance"
      | "farmingEnabled"
      | "farmingRewardRate"
      | "farmingStartTime"
      | "lockTokens"
      | "lockedBalance"
      | "owner"
      | "renounceOwnership"
      | "scatt3rToken"
      | "scatterToken"
      | "setFarmingRewardRate"
      | "startFarming"
      | "stopFarming"
      | "toggleFarming"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "StartedFarming"
      | "StoppedFarming"
      | "TokensLocked"
      | "TokensUnlocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateFarmingReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "farmingBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "farmingEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "farmingRewardRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "farmingStartTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scatt3rToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scatterToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFarmingRewardRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startFarming",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stopFarming",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toggleFarming",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateFarmingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmingEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmingRewardRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmingStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scatt3rToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scatterToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFarmingRewardRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startFarming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopFarming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleFarming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StartedFarmingEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StoppedFarmingEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    reward: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, reward: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensLockedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensUnlockedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ScatterStaking extends BaseContract {
  connect(runner?: ContractRunner | null): ScatterStaking;
  waitForDeployment(): Promise<this>;

  interface: ScatterStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateFarmingReward: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  farmingBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  farmingEnabled: TypedContractMethod<[], [boolean], "view">;

  farmingRewardRate: TypedContractMethod<[], [bigint], "view">;

  farmingStartTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  lockTokens: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  lockedBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scatt3rToken: TypedContractMethod<[], [string], "view">;

  scatterToken: TypedContractMethod<[], [string], "view">;

  setFarmingRewardRate: TypedContractMethod<
    [_newRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  startFarming: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stopFarming: TypedContractMethod<[], [void], "nonpayable">;

  toggleFarming: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateFarmingReward"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "farmingBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "farmingEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "farmingRewardRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "farmingStartTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockTokens"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lockedBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scatt3rToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "scatterToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setFarmingRewardRate"
  ): TypedContractMethod<[_newRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startFarming"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stopFarming"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleFarming"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StartedFarming"
  ): TypedContractEvent<
    StartedFarmingEvent.InputTuple,
    StartedFarmingEvent.OutputTuple,
    StartedFarmingEvent.OutputObject
  >;
  getEvent(
    key: "StoppedFarming"
  ): TypedContractEvent<
    StoppedFarmingEvent.InputTuple,
    StoppedFarmingEvent.OutputTuple,
    StoppedFarmingEvent.OutputObject
  >;
  getEvent(
    key: "TokensLocked"
  ): TypedContractEvent<
    TokensLockedEvent.InputTuple,
    TokensLockedEvent.OutputTuple,
    TokensLockedEvent.OutputObject
  >;
  getEvent(
    key: "TokensUnlocked"
  ): TypedContractEvent<
    TokensUnlockedEvent.InputTuple,
    TokensUnlockedEvent.OutputTuple,
    TokensUnlockedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StartedFarming(address,uint256)": TypedContractEvent<
      StartedFarmingEvent.InputTuple,
      StartedFarmingEvent.OutputTuple,
      StartedFarmingEvent.OutputObject
    >;
    StartedFarming: TypedContractEvent<
      StartedFarmingEvent.InputTuple,
      StartedFarmingEvent.OutputTuple,
      StartedFarmingEvent.OutputObject
    >;

    "StoppedFarming(address,uint256,uint256)": TypedContractEvent<
      StoppedFarmingEvent.InputTuple,
      StoppedFarmingEvent.OutputTuple,
      StoppedFarmingEvent.OutputObject
    >;
    StoppedFarming: TypedContractEvent<
      StoppedFarmingEvent.InputTuple,
      StoppedFarmingEvent.OutputTuple,
      StoppedFarmingEvent.OutputObject
    >;

    "TokensLocked(address,uint256)": TypedContractEvent<
      TokensLockedEvent.InputTuple,
      TokensLockedEvent.OutputTuple,
      TokensLockedEvent.OutputObject
    >;
    TokensLocked: TypedContractEvent<
      TokensLockedEvent.InputTuple,
      TokensLockedEvent.OutputTuple,
      TokensLockedEvent.OutputObject
    >;

    "TokensUnlocked(address,uint256)": TypedContractEvent<
      TokensUnlockedEvent.InputTuple,
      TokensUnlockedEvent.OutputTuple,
      TokensUnlockedEvent.OutputObject
    >;
    TokensUnlocked: TypedContractEvent<
      TokensUnlockedEvent.InputTuple,
      TokensUnlockedEvent.OutputTuple,
      TokensUnlockedEvent.OutputObject
    >;
  };
}
